### ISSUE TITLE
missing required plugin

### ISSUE THREAD

**Issue by johanpeters** [akeeba/panopticon_connector_j3#3]
Hello,
i found the joomla 3.x plugin.. btw. in the webinterface of panopticon the link for Joomla 3.x is incorrect.

after installation en enabled the plugin i am unable to connect the the site.
error message:
The “Web Services - Installer” plugin is disabled on your site

Panopticon uses the Joomla! API Application services provided by the “Web Services - Installer” plugin to ensure that all necessary extensions are installed and published on your site.

Please go to your site's backend and click on System, Manage, Extensions. Search for the “Web Services - Installer” plugin and enable it.

i checked the site but there is no extention called " web Services - installer" plugin.
searching on google to download it, i did not found it.
Discover also did not found anything.

on Joomla 4 it works out of the box.. 

can you help me get this working on Joomla 3.x sites.
i have several sites currently running Joomla 3x.. still working on new sites to migrate them to Joomla 4.x of even Joomla 5.
but i dont expect i will be ready to migrate soon.. so .. 

thanks in advance

**Comment by nikosdion** [comment]
Regarding the connector, it's already fixed in the akeeba/panopticon repo.

The connector on Joomla! 3 is a plugin called “System - Panopticon Connector for Joomla 3”. After installing it please make sure that you have enabled the plugin and its Access is set to Public.

**Comment by johanpeters** [comment]
Hello Nickolas,
thanks for your quick response.
the plugin is enabled and access is public.
still getting the error when trying to add the site.

[image: Schermafbeelding 2023-10-21 om 18.02.30.png]

site is protected with 2FA code
backend url is protected wil adminexile..

**Comment by nikosdion** [comment]
Can you please try pasting your screenshot image directly on GitHub (not in an email reply) so I can actually see what's in it, instead of just its name? :)

**Comment by johanpeters** [comment]
![Schermafbeelding 2023-10-21 om 18 02 30](https://github.com/akeeba/panopticon_connector_j3/assets/1411354/bf1557ff-ef59-4f2e-a39c-14750b34d2d0)
as requisted the screenshot of the error trying to save.

**Comment by sc00zy** [comment]
I just wanted to let you know I have exactly the same issue on a Joomla 3.10.12 site as @johanpeters. No problems with 2 other Joomla 5 websites. I installed and enabled the Panopticon plugin and entered the info in Panopticon, but then I get the same error and message.

![Schermafbeelding 2023-10-22 165630](https://github.com/akeeba/panopticon_connector_j3/assets/12911632/017d8501-53de-446a-9a6f-676352724806)

Maybe it's a Dutch only issue ;-)

**Comment by nikosdion** [comment]
Wait, that's actually a good idea. It would not be the first time I've seen a language-specific issue. Are you both using Dutch as your default language on your sites? Are your sites multi-language or single-language?

**Comment by sc00zy** [comment]
Multi-language. Both Dutch and English (sorry I wrote single-language before, but updated my comment)

**Comment by sc00zy** [comment]
Sorry... One site is single-language in Dutch and the other is multi-language in Dutch and English

**Comment by sc00zy** [comment]
The single-language site now seems to be working in Panopticon. I was able to save and close and I don't see the error message anymore. Also I can see all the informatie about extensions et cetera. No clue why it suddenly seems to work.

**Comment by nikosdion** [comment]
I created a new site with Dutch as the default language in the front-end and it works fine.

Can you email me the API endpoint and token of your site so I can see WTF is going on? I suspect there's a third party extension doing something.

**Comment by johanpeters** [comment]
i will sent the information on your @akeeba mail address

**Comment by sc00zy** [comment]
I have sent you the details using your contact form on your site. Thanks

**Comment by sc00zy** [comment]
I checked the server log and I get 401 errors when I save the new site:
401	GET /panopticon_api/index.php/v1/extensions HTTP/1.0

**Comment by nikosdion** [comment]
@johanpeters So, restoring a backup of your site on my local dev server using PHP 7.4 like your live site everything works just fine. Moreover, I noticed that your live site works fine for every API call _except_ the one that lists the extensions information. This tells me that whatever is happening has to do with your host, not your our software or your site. Please ask them if they have some kind of server protection which kicks in. If they do, let them know that it's broken: it returns an HTTP 200 OK status with an empty response body; blocked requests should return an HTTP 403 Forbidden status instead.

@sc00zy This means that you have put a (.htaccess-based) directory password protection **for the frontend of your site**. Accessing your site over an API is a regular HTTP(S) request to a URL in **your site's frontend**. If your site's frontend is password protected, your site's server rejects the connection with an HTTP 401 status. Therefore, you cannot connect to your site over the API. That's the entire point of putting a password protection, right?! Seeing that you're not the only one who didn't think about that, I'll add a special catch in the code just for this use case.

**Comment by sc00zy** [comment]
@nikosdion I allready have 4 Joomla 3 sites that can't get connected in Panopticon. None of them have frontend or backend password protection. So that can't be it. So far 6 Joomla 4/5 sites added without any problems. All the sites mentioned are on the same server.

**Comment by nikosdion** [comment]
@sc00zy You said:

> I checked the server log and I get 401 errors when I save the new site:
> 401 GET /panopticon_api/index.php/v1/extensions HTTP/1.0

There are exactly two (2) reasons for this:

1. You are using the wrong token.
2. You have frontend password protection.

FYI the token in Joomla 3 is the HMAC-SHA-256 of the site's installation path, the database hostname, the database username, the database password, the database name, your database table name prefix, and the site's secret. The only way I can think that you have NEITHER used the wrong token NOR can you connect is that you have some crappy extension which screws up the database information in the frontend. Does that ring any bells?

**Comment by Bodge-IT** [comment]
I'm here to add 1 to "users with the above issue".
On an english J3.10.12 site, Panopticon 1.0.0. PHP 7.4.33  Plugin enabled and public.  No 2FA, No html security. Tried to add entries for Panopticon install domain to WAF and panapticon_api to htaccess config in Admin Tools as wasn't sure if that was preventing connection. 
Panopticon and site are on same server.
https://mysitename.com/panopticon_api gets 404 error.


p.s. sorry, I created an issue on plg_filesystem_s3 repo by mistake...I've closed it.

**Comment by sc00zy** [comment]
Ok. Did a test:

- Setup a new subdomain
- Installed Joomla 3.10.11
- Didn't change anything, so no extra languages, htaccess.txt rename or whatsoever
- Installed the Panopticon plugin and enabled it
- Entered the endpoint url and api token in Panopticon

Result: Could not connect to remote site

Tried saving again and now my installation seems screwed when I go to manage sites overview...

![Schermafbeelding 2023-10-23 131930](https://github.com/akeeba/panopticon_connector_j3/assets/12911632/eac59aa3-ac4d-449c-953a-c74e1a239003)

**Comment by sc00zy** [comment]
> Ok. Did a test:
> 
> * Setup a new subdomain
> * Installed Joomla 3.10.11
> * Didn't change anything, so no extra languages, htaccess.txt rename or whatsoever
> * Installed the Panopticon plugin and enabled it
> * Entered the endpoint url and api token in Panopticon
> 
> Result: Could not connect to remote site
> 
> Tried saving again and now my installation seems screwed when I go to manage sites overview...
> 
> ![Schermafbeelding 2023-10-23 131930](https://user-images.githubusercontent.com/12911632/277319885-eac59aa3-ac4d-449c-953a-c74e1a239003.png)

Sorry not the overview, but when I click on "new" when on the manage sites overview page.

Edit: Also other actions like edit and delete result in the same error.

Edit 2: After logging out and in, I'm now able to use the actions "new, edit and delete" again.

**Comment by nikosdion** [comment]
Each one of you seems to have a different issue. It is impossible for me to help any one of you in a meaningful way when there are at least three completely unrelated discussions going on in each thread.

Here's what you have to do.

First, install the following dev release: https://www.akeeba.com/download/panopticon-dev/1-0-1-dev202310231224.html

Then, go to Administration, System Configuration, System tab, System Preferences area and enable Debug System.

Now, retry adding your site. You will receive far more detailed troubleshooting information which will help you understand what is going on.

If you still need help, submit **a new issue, including the detailed troubleshooting information**.

Also note that if an unrelated person starts commenting on an issue where I am helping a different person to tell me about their own problem, I am going to delete that comment. Trying to figure out what each one of you is trying to do is impossible and ultimately slows me down to the point I am not productive anymore.

Thank you for your understanding. I am closing this issue now.

**Comment by nikosdion** [comment]
There seemed to be a problem when trying to connect to sites which didn't have SEF URLs with URL rewriting enabled on Joomla! 3. This has been addressed in the [latest dev release](https://www.akeeba.com/download/panopticon-dev/1-0-1-dev202310231802.html). Please install and test.

Note that the first time you get an error, it might suggest that you use a different Endpoint URL in the form `https://www.example.com/index.php/panopticon_api`. Note the `index.php/` in there. **This is a manual action**. Panopticon will **NOT** do that for you, it will only present it as a suggestion.

Moreover, the connector would erroneously recommend the endpoint URL `https://www.example.com/index.php?/panopticon_api` (note the question mark) on some Joomla! 3 sites. This was replaced with the Joomla! 4 API URL by Panopticon, therefore you got an error. This is now caught by Panopticon when you try to create a new site and converted _automatically_ to the correct Endpoint URL in the form `https://www.example.com/index.php/panopticon_api`. This is an automatic action; there is no need for you to do anything.

**Comment by johanpeters** [comment]
hello @nikosdion .. this issue can be closed.. (as you reply'd already)
i will report a seperate issue .. i did some futher testing and trouble shouting on this specific toppic of not connecting.

i have no close option.. so if you can close it.. thnx..

**Comment by nikosdion** [comment]
It's already closed; I had closed all these duplicate issues about the same problem last week when I reproduced it and fixed it 😄
